package yzarr.auth.model.enums;

public enum ErrorCode {
    INVALID_CREDENTIALS,
    PASSWORD_IS_TOO_SHORT,
    EMAIL_ALREADY_EXISTS,
    INVALID_EMAIL_FORMAT,
    EMAIL_IS_NOT_VERIFIED,
    NO_REFRESH_TOKEN,
    INVALID_REFRESH_TOKEN,
    NO_EMAIL_VERIFICATION_TOKEN,
    INVALID_EMAIL_VERIFICATION_TOKEN,
    EMAIL_IS_ALREADY_VERIFIED,
    NO_ACCESS_TOKEN,
    INVALID_ACCESS_TOKEN,

}
